# My 1st line

Hello World

## 2nd header

###### up to  5 # it seems

- Understand the different types of variables in python
- Is Juptyer related to Jupiter?


1. Go through different types of variables

2. run through e.g for linear algebra

In [1]:
x = 2.5
y = 3.5

# here i print x+y
# run one line of code or line by line
# highlight then click the button above
print("x+y")


z = x + y
print(z)

t = "Hello World"
r = " how are you?"

print("t+r")
print(t+r)

boo = True
foo = False


x+y
6.0
t+r
Hello World how are you?


In [2]:
x


2.5

 ## Compute the scalar product of 2 vectors
 
In mathematics, the dot product or scalar product is an algebraic operation that takes two equal-length sequences of numbers (usually coordinate vectors) and returns a single number. 

> we can calculate it this way:

        a · b = ax × bx + ay × by
        
Hint: [Dot Product](https://www.mathsisfun.com/algebra/vectors-dot-product.html)



In [2]:
import numpy as np
a = np.arange(15).reshape(3, 5)

In [4]:
import numpy
b = numpy.arange(15).reshape(3, 5)

In [5]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
b


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [7]:
type(b
)

numpy.ndarray

In [8]:
a


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [13]:
a = np.array([-12,16])
b = np.array([12,9])
c = a[0]+b[0]+a[1]+b[1]

print("product : ",c)
print("product dot : ", np.dot(a,b))

product :  25
product dot :  0


## 2. Compute the cross product of two vectors

> When a and b start at the origin point (0,0,0), the Cross Product will end at:

        cx = aybz − azby
        cy = azbx − axbz
        cz = axby − aybx
        
Hint: [Cross Product](https://www.mathsisfun.com/algebra/vectors-cross-product.html)


In [15]:
x = [[1,2,3], [4,5,6]]
y = [[4,5,6], [1,2,3]]

v = np.cross(x, y)

print("cross product :")
print (v)

cross product :
[[-3  6 -3]
 [ 3 -6  3]]


In [26]:
# Program to add 2 matrices using nested loop

X = [[12, 7, 3],
    [4, 5, 6],
    [7, 8, 9]]

Y = [[5, 8, 1],
    [6, 7, 3],
    [4, 5, 9]]

result = [[0,0,0],
         [0,0,0],
         [0,0,0]]



In [27]:
for i in range(len(X)):
    # iterate through columns
    for j in range(len(X[0])):
        result[i][j] = X[i][j] + Y[i][j]
        
    

In [28]:
print(result)

[[17, 15, 4], [10, 12, 9], [11, 13, 18]]


In [29]:
np.add(X, Y)

array([[17, 15,  4],
       [10, 12,  9],
       [11, 13, 18]])

In [30]:
# 3x3 matrix

X = np.array([[12, 7, 3],
    [4, 5, 6],
    [7, 8, 9]]
            )
#3x4 matrix

Y = np.array([[5, 8, 1, 2],
            [6, 7, 3, 0],
            [4, 5, 9, 1]])



In [31]:
X*Y

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

In [32]:
np.dot(X,Y)

array([[114, 160,  60,  27],
       [ 74,  97,  73,  14],
       [119, 157, 112,  23]])

In [37]:
m1 = np.matrix([[-2, 2, -3], [-1, 1, 3], [2,0,-1]])
det = np.linalg.det(m1)

In [38]:
det


17.999999999999996

In [39]:
?det

In [40]:
a = np.array([[1.,2.],[3.,4.]])

In [41]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [42]:
b = np.array([[4,5,5],[2,4,-9],[3,1,-1]])

In [51]:
c = np.linalg.inv(b)
print(c)

[[-0.03225806 -0.06451613  0.41935484]
 [ 0.16129032  0.12258065 -0.29677419]
 [ 0.06451613 -0.07096774 -0.03870968]]


In [44]:
det= np.linalg.det(b)

In [45]:
print(det)

-155.00000000000003


In [47]:
d = np.array([2,0.5,0.75])

In [48]:
e = np.dot(c,d)

In [49]:
print(e)

[0.21774194 0.16129032 0.06451613]
